// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

// interface CloudflareEnv {
// }

declare global {
    namespace NodeJS {
      interface ProcessEnv {
        DB: D1Database;
      }
    }
  }
   
  export {};